export const latestGamesList = [
  {
    id: 101,
    title: "Crysis",
    image: "https://wallpapercave.com/wp/wp10904883.jpg",
    text: "Experience the ultimate sci-fi shooter with Crysis.",
    genre: "First-Person Shooter",
    rating: 4.5,
    price: 699,
    platforms: [
      "PC",
      "PlayStation 3",
      "PlayStation 4",
      "Xbox 360",
      "Xbox One",
      "Nintendo Switch",
    ],
    description:
      "A visually groundbreaking sci-fi shooter where players utilize a highly advanced Nanosuit with unique abilities—Armor, Strength, Speed, and Cloak—to survive and battle extraterrestrial threats on a tropical island.",
  },
  {
    id: 102,
    title: "Halo",
    image: "https://wallpapercave.com/wp/wp12028543.jpg",
    text: "Step into the armor of the Master Chief in the legendary Halo universe.",
    genre: "First-Person Shooter",
    rating: 4.7,
    price: 3349,
    platforms: ["Xbox", "Xbox 360", "Xbox One", "Xbox Series X/S", "PC"],
    description:
      "An iconic, genre-defining sci-fi franchise following the cybernetically enhanced supersoldier Master Chief and his AI companion Cortana as they defend humanity against the alien alliance known as the Covenant.",
  },
  {
    id: 103,
    title: "Tomb Raider",
    image: "https://wallpapercave.com/wp/wc1692298.jpg",
    text: "Join Lara Croft on her cinematic survival expeditions in Tomb Raider.",
    genre: "Action-Adventure",
    rating: 4.4,
    price: 999,
    platforms: [
      "PC",
      "PlayStation 3",
      "PlayStation 4",
      "Xbox 360",
      "Xbox One",
      "macOS",
      "Linux",
    ],
    description:
      "A cinematic action-adventure series focused on exploration, puzzle-solving, and survival, detailing the gritty origin story of Lara Croft as she transforms from an inexperienced researcher into a hardened survivor.",
  },
  {
    id: 104,
    title: "Mortal Kombat",
    image: "https://wallpapercave.com/wp/wp13016862.png",
    text: "Test your might in the iconic and brutal arenas of Mortal Kombat.",
    genre: "Fighting",
    rating: 4.6,
    price: 2999,
    platforms: [
      "PC",
      "PlayStation 4",
      "PlayStation 5",
      "Xbox One",
      "Xbox Series X/S",
      "Nintendo Switch",
    ],
    description:
      "A fiercely competitive and legendary fighting game franchise famous for its deep lore, diverse roster of martial artists, and over-the-top, bloody 'Fatality' finishing moves.",
  },
  {
    id: 105,
    title: "Ninja Gaiden",
    image: "https://wallpapercave.com/wp/wp2472220.jpg",
    text: "Master the way of the ninja with Ryu Hayabusa in Ninja Gaiden.",
    genre: "Hack and Slash",
    rating: 4.3,
    price: 2499,
    platforms: [
      "PC",
      "PlayStation 3",
      "PlayStation 4",
      "Xbox",
      "Xbox 360",
      "Xbox One",
      "Nintendo Switch",
    ],
    description:
      "A fast-paced, highly demanding action series that puts players in control of master ninja Ryu Hayabusa, known for its deep combat mechanics and famously punishing difficulty curve.",
  },
  {
    id: 106,
    title: "God Of War",
    image: "https://wallpapercave.com/wp/3b6ChfH.jpg",
    text: "Embrace the fury of Sparta alongside Kratos in God Of War.",
    genre: "Hack and Slash",
    rating: 4.9,
    price: 3299,
    platforms: [
      "PlayStation 2",
      "PlayStation 3",
      "PlayStation 4",
      "PlayStation 5",
      "PC",
    ],
    description:
      "An epic, narrative-driven saga charting the blood-soaked journey of Kratos, the Ghost of Sparta, as he seeks vengeance against the Greek gods and later navigates the perilous realms of Norse mythology.",
  },
  {
    id: 107,
    title: "Assasins Creed",
    image: "https://wallpapercave.com/wp/waX62fC.jpg",
    text: "Explore rich, historical open worlds in the Assassins Creed franchise.",
    genre: "Stealth",
    rating: 4.5,
    price: 2499,
    platforms: [
      "PC",
      "PlayStation 3",
      "PlayStation 4",
      "PlayStation 5",
      "Xbox 360",
      "Xbox One",
      "Xbox Series X/S",
    ],
    description:
      "A massively popular open-world series centering on a millennia-old secret war between the Assassin Brotherhood, who fight for free will, and the Templar Order, who seek control, set across beautifully recreated historical eras.",
  },
  {
    id: 108,
    title: "Need For Speed: Hot Pursuit",
    image: "https://wallpapercave.com/wp/wp10553422.jpg",
    text: "Unleash a savage sense of speed both as an outlaw and a cop.",
    genre: "Racing",
    rating: 4.2,
    price: 1499,
    platforms: [
      "PlayStation 3",
      "Android",
      "Xbox 360",
      "Microsoft Windows",
      "Wii",
      "iOS",
      "Windows Phone",
      "webOS",
      "Java",
    ],
    description:
      "Feel the thrill of the chase and the rush of escape in Need for Speed™ Hot Pursuit Remastered. Unleash a savage sense of speed both as an outlaw and a cop in the world's hottest high-performance cars.",
  },
];

export const gamesCategories = [
  {
    id: 1,
    name: "RPG",
    backgroundImage: "https://wallpapercave.com/wp/wp6823992.jpg",
  },
  {
    id: 2,
    name: "Sandbox",
    backgroundImage: "https://wallpapercave.com/wp/wp2777682.jpg",
  },
  {
    id: 3,
    name: "Sports",
    backgroundImage: "https://wallpapercave.com/wp/wp12593837.jpg",
  },
  {
    id: 4,
    name: "FPS",
    backgroundImage: "https://wallpapercave.com/wp/wp7716299.jpg",
  },
  {
    id: 5,
    name: "Action-Adventure",
    backgroundImage: "https://wallpapercave.com/wp/wp14035067.webp",
  },
  {
    id: 6,
    name: "Fighting",
    backgroundImage: "https://wallpapercave.com/wp/wp13707882.png",
  },
  {
    id: 7,
    name: "Horror",
    backgroundImage: "https://wallpapercave.com/wp/wp12116718.jpg",
  },
  {
    id: 8,
    name: "Racing",
    backgroundImage: "https://wallpapercave.com/wp/wp12405347.jpg",
  },
  {
    id: 9,
    name: "Strategy",
    backgroundImage: "https://wallpapercave.com/wp/wp3805966.jpg",
  },
];

export const allGames = [
  {
    id: 1,
    title: "Cyberpunk 2077",
    image: "https://wallpapercave.com/wp/wp6823992.jpg",
    text: "Welcome to Night City, a megalopolis obsessed with power.",
    rating: 4.2,
    price: 2999,
    discount: 20,
    genre: "RPG",
    description:
      "An open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour, and body modification.",
    platforms: ["PC", "PS5", "Xbox Series X"],
    images: [
      "https://wallpapercave.com/wp/wp6823992.jpg",
      "https://wallpapercave.com/wp/wp6072778.png",
      "https://wallpapercave.com/wp/wp6823990.jpg",
      "https://wallpapercave.com/wp/wp6736053.jpg",
      "https://wallpapercave.com/wp/wp6824012.jpg",
    ],
  },
  {
    id: 13,
    title: "Minecraft",
    image: "https://wallpapercave.com/wp/wp2777682.jpg",
    text: "Explore infinite worlds and build everything from simple homes to castles.",
    rating: 4.7,
    price: 1999,
    genre: "Sandbox",
    description:
      "Explore infinite worlds and build everything from the simplest of homes to the grandest of castles.",
    platforms: ["PC", "PS4", "Xbox One", "Nintendo Switch", "iOS", "Android"],
    images: [
      "https://wallpapercave.com/wp/wp2777682.jpg",
      "https://wallpapercave.com/wp/wp2896230.png",
      "https://wallpapercave.com/wp/wp2477626.jpg",
      "https://wallpapercave.com/wp/wp2896241.jpg",
      "https://wallpapercave.com/wp/wp2652288.jpg",
    ],
  },
  {
    id: 9,
    title: "FIFA 24",
    image: "https://wallpapercave.com/wp/wp12593837.jpg",
    text: "Experience the World's Game with unrivaled realism.",
    rating: 4.0,
    price: 3499,
    discount: 15,
    genre: "Sports",
    description:
      "Experience the world's game with unparalleled realism, featuring the biggest tournaments, leagues, and players.",
    platforms: ["PC", "PS5", "Xbox Series X", "Nintendo Switch"],
    images: [
      "https://wallpapercave.com/wp/wp12593837.jpg",
      "https://wallpapercave.com/wp/wp11884019.jpg",
      "https://wallpapercave.com/wp/wp12562477.jpg",
      "https://wallpapercave.com/wp/wp12562484.jpg",
      "https://wallpapercave.com/wp/wp12562492.jpg",
    ],
  },
  {
    id: 5,
    title: "Call of Duty: MWIII",
    image: "https://wallpapercave.com/wp/wp13002741.jpg",
    text: "Adapt or die in a fight against the ultimate threat.",
    rating: 4.1,
    price: 5599,
    genre: "FPS",
    description:
      "Adapt or die in a fight against the ultimate threat, featuring iconic multiplayer maps and a cinematic campaign.",
    platforms: ["PC", "PS5", "Xbox Series X"],
    images: [
      "https://wallpapercave.com/wp/wp13002741.jpg",
      "https://wallpapercave.com/wp/wp13127006.jpg",
      "https://wallpapercave.com/wp/wp13127035.jpg",
      "https://wallpapercave.com/wp/wp12995280.jpg",
      "https://wallpapercave.com/wp/wp13132293.jpg",
    ],
  },
  {
    id: 21,
    title: "Elden Ring",
    image: "https://wallpapercave.com/wp/wp14808661.webp",
    text: "Rise, Tarnished, and be guided by grace to brandish the Elden Ring.",
    rating: 4.9,
    price: 3599,
    genre: "Action-Adventure",
    description:
      "Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring in a massive dark fantasy world.",
    platforms: ["PC", "PS5", "Xbox Series X"],
    images: [
      "https://wallpapercave.com/wp/wp14808661.webp",
      "https://wallpapercave.com/wp/wp13489035.jpg",
      "https://wallpapercave.com/wp/wp14808666.webp",
      "https://wallpapercave.com/wp/wp14035067.webp",
      "https://wallpapercave.com/wp/wp14808672.webp",
    ],
  },
  {
    id: 37,
    title: "Street Fighter 6",
    image: "https://wallpapercave.com/wp/wp12751223.jpg",
    text: "The evolving fighting arena built for casual and pro warriors alike.",
    rating: 4.6,
    price: 3999,
    genre: "Fighting",
    description:
      "Powered by a proprietary engine, experience a new era of fighting games with evolved mechanics and vibrant visuals.",
    platforms: ["PC", "PS5", "Xbox Series X"],
    images: [
      "https://wallpapercave.com/wp/wp12751223.jpg",
      "https://wallpapercave.com/wp/wp12500330.jpg",
      "https://wallpapercave.com/wp/wp13707850.jpg",
      "https://wallpapercave.com/wp/wp13707882.png",
      "https://wallpapercave.com/wp/wp12931429.jpg",
    ],
  },
  {
    id: 29,
    title: "Resident Evil 4 (Remake)",
    image: "https://wallpapercave.com/wp/wp12116688.jpg",
    text: "Survival is just the beginning in this reimagined horror masterpiece.",
    rating: 4.8,
    price: 3599,
    genre: "Horror",
    description:
      "Survival is just the beginning in this fully reimagined survival-horror masterpiece featuring updated modern combat.",
    platforms: ["PC", "PS5", "Xbox Series X"],
    images: [
      "https://wallpapercave.com/wp/wp12116688.jpg",
      "https://wallpapercave.com/wp/wp12116675.png",
      "https://wallpapercave.com/wp/wp11811996.jpg",
      "https://wallpapercave.com/wp/wp12116718.jpg",
      "https://wallpapercave.com/wp/wp11812016.jpg",
    ],
  },
  {
    id: 33,
    title: "Forza Horizon 5",
    image: "https://wallpapercave.com/wp/wp12405465.jpg",
    text: "Your ultimate Horizon Adventure awaits! Explore vibrant open worlds.",
    rating: 4.7,
    price: 3499,
    genre: "Racing",
    description:
      "Lead breathtaking expeditions across the vibrant and ever-evolving open world landscapes of Mexico in hundreds of world-class cars.",
    platforms: ["PC", "Xbox Series X", "Xbox One"],
    images: [
      "https://wallpapercave.com/wp/wp12405465.jpg",
      "https://wallpapercave.com/wp/wp12405298.jpg",
      "https://wallpapercave.com/wp/wp12405347.jpg",
      "https://wallpapercave.com/wp/wp11439202.jpg",
      "https://wallpapercave.com/wp/wp12405389.jpg",
    ],
  },
  {
    id: 25,
    title: "Civilization VI",
    image: "https://wallpapercave.com/wp/wp3805937.jpg",
    text: "Build an empire to stand the test of time.",
    rating: 4.4,
    price: 2499,
    discount: 75,
    genre: "Strategy",
    description:
      "A turn-based strategy game in which you attempt to build an empire to stand the test of time, expanding your empire across the map.",
    platforms: ["PC", "PS4", "Xbox One", "Nintendo Switch", "iOS"],
    images: [
      "https://wallpapercave.com/wp/wp3805937.jpg",
      "https://wallpapercave.com/wp/wp2114487.jpg",
      "https://wallpapercave.com/wp/wp3805951.jpg",
      "https://wallpapercave.com/wp/wp2114461.jpg",
      "https://wallpapercave.com/wp/wp3805966.jpg",
    ],
  },
];

export const GOTYList = [
  {
    id: 2025,
    title: "Clair Obscur: Expedition 33",
    developer: "Sandfall Interactive",
    images: [
      "https://wallpapercave.com/wp/wp15037158.webp",
      "https://wallpapercave.com/wp/wp15037159.webp",
      "https://wallpapercave.com/wp/wp15037157.webp",
      "https://wallpapercave.com/wp/wp15037156.webp",
      "https://wallpapercave.com/wp/wp15037155.webp",
    ],
    year: 2025,
    awards: ["Game of the Year", "Best RPG", "Best Art Direction"],
    description:
      "A turn-based RPG featuring real-time mechanics where you lead the Expeditionary force to destroy the Paintress before she paints death upon the world.",
    rating: 4.8,
    isWinner: true,
    category: "Game of the Year",
    platforms: ["PC", "PS5", "Xbox Series X"],
    genre: "RPG",
    discount: 20,
    price: 49.99,
    recommendedSystemRequirements: {
      os: "Windows 11 (64-bit)",
      processor: "Intel Core i7-12700K / AMD Ryzen 7 7700X",
      memory: "16 GB RAM",
      graphics: "NVIDIA GeForce RTX 4070 / AMD Radeon RX 7800 XT",
      vram: "12 GB",
      directX: "Version 12",
      storage: "90 GB available space (SSD required)",
    },
  },
  {
    id: 2024,
    title: "Astro Bot",
    developer: "Team Asobi",
    images: [
      "https://wallpapercave.com/wp/wp14428873.jpg",
      "https://wallpapercave.com/wp/wp8415018.jpg",
      "https://wallpapercave.com/wp/wp14428871.jpg",
      "https://wallpapercave.com/wp/wp12002657.jpg",
      "https://wallpapercave.com/wp/wp8395512.jpg",
    ],
    year: 2024,
    awards: ["Game of the Year", "Best Game Direction", "Best Family Game"],
    description:
      "An celebration of PlayStation history wrapped inside a masterpiece of a 3D platformer featuring creative level designs and deep DualSense integration.",
    rating: 4.9,
    isWinner: true,
    category: "Game of the Year",
    platforms: ["PS5"],
    genre: "Platformer",
    discount: 0,
    price: 59.99,
    recommendedSystemRequirements: {
      os: "N/A (PlayStation 5 Exclusive)",
      processor: "N/A",
      memory: "N/A",
      graphics: "N/A",
      vram: "N/A",
      directX: "N/A",
      storage: "66 GB available space (Internal SSD)",
    },
  },
  {
    id: 2023,
    title: "Baldur's Gate 3",
    developer: "Larian Studios",
    images: [
      "https://wallpapercave.com/wp/wp6376877.jpg",
      "https://wallpapercave.com/wp/wp7527718.jpg",
      "https://wallpapercave.com/wp/wp8231508.jpg",
      "https://wallpapercave.com/wp/wp7527536.jpg",
      "https://wallpapercave.com/wp/wp8231682.jpg",
    ],
    year: 2023,
    awards: [
      "Game of the Year",
      "Best RPG",
      "Best Narrative",
      "Player's Voice",
    ],
    description:
      "An expansive, player-choice-driven RPG set in the universe of Dungeons & Dragons, boasting deep tactical turn-based combat and rich storytelling.",
    rating: 4.9,
    isWinner: true,
    category: "Game of the Year",
    platforms: ["PC", "PS5", "Xbox Series X"],
    genre: "RPG",
    discount: 0,
    price: 59.99,
    recommendedSystemRequirements: {
      os: "Windows 10 / 11 (64-bit)",
      processor: "Intel Core i7-8700K / AMD Ryzen 5 3600X",
      memory: "16 GB RAM",
      graphics: "NVIDIA GeForce RTX 2060 Super / AMD Radeon RX 5700 XT",
      vram: "8 GB",
      directX: "Version 11",
      storage: "150 GB available space (SSD required)",
    },
  },
  {
    id: 2022,
    title: "Elden Ring",
    developer: "FromSoftware",
    images: [
      "https://wallpapercave.com/wp/wp14808661.webp",
      "https://wallpapercave.com/wp/wp13489035.jpg",
      "https://wallpapercave.com/wp/wp14808666.webp",
      "https://wallpapercave.com/wp/wp14035067.webp",
      "https://wallpapercave.com/wp/wp14808672.webp",
    ],
    year: 2022,
    awards: [
      "Game of the Year",
      "Best Game Direction",
      "Best Art Direction",
      "Best RPG",
    ],
    description:
      "Rise, Tarnished, and explore a massive open world filled with challenging bosses, deep lore, and dark fantasy visuals crafted by FromSoftware.",
    rating: 4.9,
    isWinner: true,
    category: "Game of the Year",
    platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X"],
    genre: "Action RPG",
    discount: 0,
    price: 59.99,
    recommendedSystemRequirements: {
      os: "Windows 10 / 11 (64-bit)",
      processor: "Intel Core i7-8700K / AMD Ryzen 5 3600X",
      memory: "16 GB RAM",
      graphics: "NVIDIA GeForce GTX 1070 / AMD Radeon RX Vega 56",
      vram: "8 GB",
      directX: "Version 12",
      storage: "60 GB available space (SSD recommended)",
    },
  },
  {
    id: 2021,
    title: "It Takes Two",
    developer: "Hazelight Studios",
    images: [
      "https://wallpapercave.com/wp/wp14614899.jpg",
      "https://wallpapercave.com/wp/wp14614900.jpg",
      "https://wallpapercave.com/wp/wp14614906.jpg",
      "https://wallpapercave.com/wp/wp14614909.jpg",
      "https://wallpapercave.com/wp/wp14614912.jpg",
    ],
    year: 2021,
    awards: ["Game of the Year", "Best Family Game", "Best Multiplayer Game"],
    description:
      "An genre-bending co-op adventure platformer built purely for two players, exploring themes of relationships through highly varied gameplay.",
    rating: 4.8,
    isWinner: true,
    category: "Game of the Year",
    platforms: [
      "PC",
      "PS4",
      "PS5",
      "Xbox One",
      "Xbox Series X",
      "Nintendo Switch",
    ],
    genre: "Co-op Platformer",
    discount: 0,
    price: 39.99,
    recommendedSystemRequirements: {
      os: "Windows 10 (64-bit)",
      processor: "Intel Core i5-3570K / AMD FX-8350",
      memory: "16 GB RAM",
      graphics: "NVIDIA GeForce GTX 980 / AMD Radeon R9 290X",
      vram: "4 GB",
      directX: "Version 11",
      storage: "50 GB available space",
    },
  },
];

export const gamesReviews = [
  {
    id: 1,
    userName: "GamerPro2024",
    userAvatar: "https://picsum.photos/40/40?random=1",
    rating: 5,
    comment:
      "Absolutely incredible game! The graphics are stunning and the storyline keeps you hooked from start to finish. The combat system is intuitive yet deep, offering hours of engaging gameplay.",
    date: "2024-01-15",
    helpful: 24,
    gameTitle: "Cyberpunk 2077",
  },
  {
    id: 2,
    userName: "RetroGamer",
    userAvatar: "https://picsum.photos/40/40?random=2",
    rating: 4,
    comment:
      "Great RPG with amazing world-building. Some bugs here and there, but the overall experience is fantastic. The character development system is one of the best I've seen.",
    date: "2024-01-10",
    helpful: 18,
    gameTitle: "The Witcher 3",
  },
  {
    id: 3,
    userName: "CasualPlayer",
    userAvatar: "https://picsum.photos/40/40?random=3",
    rating: 3,
    comment:
      "Decent game, but not for everyone. The learning curve is steep and some mechanics feel outdated. Still, if you enjoy sports games, it's worth a try.",
    date: "2024-01-08",
    helpful: 7,
    gameTitle: "FIFA 24",
  },
  {
    id: 4,
    userName: "FPSFanatic",
    userAvatar: "https://picsum.photos/40/40?random=4",
    rating: 5,
    comment:
      "Best CoD game in years! The multiplayer is addictive and the campaign is intense. Graphics are top-notch and the sound design is incredible.",
    date: "2024-01-05",
    helpful: 31,
    gameTitle: "Call of Duty: Modern Warfare III",
  },
  {
    id: 5,
    userName: "SandboxLover",
    userAvatar: "https://picsum.photos/40/40?random=5",
    rating: 4,
    comment:
      "Minecraft never gets old! The creativity it inspires is unmatched. Perfect for all ages and great for educational purposes too.",
    date: "2024-01-03",
    helpful: 15,
    gameTitle: "Minecraft",
  },
  {
    id: 6,
    userName: "OpenWorldEnthusiast",
    userAvatar: "https://picsum.photos/40/40?random=6",
    rating: 5,
    comment:
      "Rockstar has done it again! GTA V is a masterpiece of open-world gaming. The story, characters, and freedom are unparalleled.",
    date: "2024-01-01",
    helpful: 42,
    gameTitle: "Grand Theft Auto V",
  },
];
