import type { Category, GameDetail, GOTYGameDetail } from "./types/authTypes";

export const latestGamesList: GameDetail[] = [
  {
    id: 101,
    title: "Crysis",
    image:
      "https://scontent.fpnq7-8.fna.fbcdn.net/v/t39.30808-6/496943855_4284837781747712_1834308046476137887_n.jpg?stp=dst-jpg_tt6&cstp=mx1920x1080&ctp=s1920x1080&_nc_cat=100&ccb=1-7&_nc_sid=0b6b33&_nc_ohc=6Z6Z-cs1Il4Q7kNvwEo1gUU&_nc_oc=AdqbLNL2N4buwJlnf69n31-eYlRBBNPY2rLE4QFn7gfNGg5cuxbsWGeonH88ONr496L63N3f-qjiHn584RLcS4Fn&_nc_zt=23&_nc_ht=scontent.fpnq7-8.fna&_nc_gid=3ipZJuvr6vMtANkFC82Piw&_nc_ss=7b2a8&oh=00_Af_w1dheo6x9kgKkcei5RNg0pFAS1ONMkPvrH5Ah42YmHA&oe=6A2B4066",
    text: "Experience the ultimate sci-fi shooter with Crysis.",
    genre: "First-Person Shooter",
    rating: 4.5,
    price: 699,
    platforms: [
      "PC",
      "PlayStation 3",
      "PlayStation 4",
      "Xbox 360",
      "Xbox One",
      "Nintendo Switch",
    ],
    description:
      "A visually groundbreaking sci-fi shooter where players utilize a highly advanced Nanosuit with unique abilities—Armor, Strength, Speed, and Cloak—to survive and battle extraterrestrial threats on a tropical island.",
  },
  {
    id: 102,
    title: "Halo",
    image:
      "https://scontent.fpnq7-4.fna.fbcdn.net/v/t39.30808-6/495817640_4284816535083170_5491099831647143716_n.jpg?stp=dst-jpg_tt6&cstp=mx1920x1080&ctp=s1920x1080&_nc_cat=105&ccb=1-7&_nc_sid=0b6b33&_nc_ohc=CDBt5tmzzfsQ7kNvwE_TH4O&_nc_oc=AdrCThBlRKSQQZUSU8b1hKYciAjUk-wk_xr7BaAzGRoFyjHpVesvwsb9Jt7rGhI6FlQCzwbz71mxqR-D9kymr765&_nc_zt=23&_nc_ht=scontent.fpnq7-4.fna&_nc_gid=jjjjMYhG2mL3sSQvnlQq5Q&_nc_ss=7b2a8&oh=00_Af9QB-VB9dKvqQc4V6pVuSMkPRIMLFcXKg1Cihtj6Kc5lw&oe=6A2B27EB",
    text: "Step into the armor of the Master Chief in the legendary Halo universe.",
    genre: "First-Person Shooter",
    rating: 4.7,
    price: 3349,
    platforms: ["Xbox", "Xbox 360", "Xbox One", "Xbox Series X/S", "PC"],
    description:
      "An iconic, genre-defining sci-fi franchise following the cybernetically enhanced supersoldier Master Chief and his AI companion Cortana as they defend humanity against the alien alliance known as the Covenant.",
  },
  {
    id: 103,
    title: "Tomb Raider",
    image:
      "https://scontent.fpnq7-8.fna.fbcdn.net/v/t39.30808-6/495810894_4284663508431806_3207286339331359209_n.jpg?stp=dst-jpg_tt6&cstp=mx1920x1080&ctp=s1920x1080&_nc_cat=100&ccb=1-7&_nc_sid=0b6b33&_nc_ohc=C2SEuy5qNvoQ7kNvwHzn50p&_nc_oc=Ado_4gz69noev_fQQzdV8IPXw_rtBqLGY727NSwD6mHdaUMtBf0kNPc_Qy-0iN-cv2TCJN8_8gWIWnxSXZiZSTbq&_nc_zt=23&_nc_ht=scontent.fpnq7-8.fna&_nc_gid=DIWewWm17JjufPxdvRXZLA&_nc_ss=7b2a8&oh=00_Af-SZmuF08puSBCVbEeWGm-Vdfto_sgo2nItq1QgTTimow&oe=6A2B35F4",
    text: "Join Lara Croft on her cinematic survival expeditions in Tomb Raider.",
    genre: "Action-Adventure",
    rating: 4.4,
    price: 999,
    platforms: [
      "PC",
      "PlayStation 3",
      "PlayStation 4",
      "Xbox 360",
      "Xbox One",
      "macOS",
      "Linux",
    ],
    description:
      "A cinematic action-adventure series focused on exploration, puzzle-solving, and survival, detailing the gritty origin story of Lara Croft as she transforms from an inexperienced researcher into a hardened survivor.",
  },
  {
    id: 104,
    title: "Mortal Kombat",
    image:
      "https://scontent.fpnq7-6.fna.fbcdn.net/v/t39.30808-6/496006676_4285181185046705_2630935143941272565_n.jpg?stp=dst-jpg_tt6&cstp=mx1920x1080&ctp=s1920x1080&_nc_cat=111&ccb=1-7&_nc_sid=0b6b33&_nc_ohc=RPnahlYseIYQ7kNvwGC-bZ0&_nc_oc=AdoHV6JJUcPmuLx0e5NG0afEUCsQMNCkovkugepXlcERaqj8J_AbE1sORVuA6DP2Y-8ybLhICcbWHf7c8rKWT0m5&_nc_zt=23&_nc_ht=scontent.fpnq7-6.fna&_nc_gid=mFfUOo4zbvqiD5yIpGXSFw&_nc_ss=7b2a8&oh=00_Af_TwzpYPx1Ut9uZ26-yzbP_mrzOV5nhwOsuDb92X1YBIw&oe=6A2B2DE2",
    text: "Test your might in the iconic and brutal arenas of Mortal Kombat.",
    genre: "Fighting",
    rating: 4.6,
    price: 2999,
    platforms: [
      "PC",
      "PlayStation 4",
      "PlayStation 5",
      "Xbox One",
      "Xbox Series X/S",
      "Nintendo Switch",
    ],
    description:
      "A fiercely competitive and legendary fighting game franchise famous for its deep lore, diverse roster of martial artists, and over-the-top, bloody 'Fatality' finishing moves.",
  },
  {
    id: 105,
    title: "Ninja Gaiden",
    image:
      "https://scontent.fpnq7-6.fna.fbcdn.net/v/t39.30808-6/495020140_4275651165999707_6564449505237608161_n.jpg?stp=dst-jpg_tt6&cstp=mx1920x1080&ctp=s1920x1080&_nc_cat=104&ccb=1-7&_nc_sid=0b6b33&_nc_ohc=WIiwT-7hrdgQ7kNvwFrjjcL&_nc_oc=Adq_dRRacBhiMscm7mR6Li8P5LlaU4MpiTQDQjilNzx7U2bMd5b5lbzMvHWosCTY6b253Vxv9cQUcur5WludUU01&_nc_zt=23&_nc_ht=scontent.fpnq7-6.fna&_nc_gid=ZppGSy_DGrwP1dWbUHVe9A&_nc_ss=7b2a8&oh=00_Af9idtSYEOKFXPub18ZIh-bgUO464PCISu-NFzO6rRTLzQ&oe=6A2B46E6",
    text: "Master the way of the ninja with Ryu Hayabusa in Ninja Gaiden.",
    genre: "Hack and Slash",
    rating: 4.3,
    price: 2499,
    platforms: [
      "PC",
      "PlayStation 3",
      "PlayStation 4",
      "Xbox",
      "Xbox 360",
      "Xbox One",
      "Nintendo Switch",
    ],
    description:
      "A fast-paced, highly demanding action series that puts players in control of master ninja Ryu Hayabusa, known for its deep combat mechanics and famously punishing difficulty curve.",
  },
  {
    id: 106,
    title: "God Of War",
    image:
      "https://scontent.fpnq7-9.fna.fbcdn.net/v/t39.30808-6/495225098_4275442676020556_2126645081395022291_n.jpg?stp=dst-jpg_tt6&cstp=mx1920x1080&ctp=s1920x1080&_nc_cat=108&ccb=1-7&_nc_sid=0b6b33&_nc_ohc=jBwmOjpTVpMQ7kNvwEbgzeT&_nc_oc=AdpnuHmrzSPuy7-e3DpLF4Mv9gx3aKCowGvCY9A8knR4LJvXKJh7km-qOKtlojfg6MLX-BGIxuk4sYcZn10__v5Q&_nc_zt=23&_nc_ht=scontent.fpnq7-9.fna&_nc_gid=I9JRW1qXTTkNrvYqBVLLHA&_nc_ss=7b2a8&oh=00_Af9XFk5P0cW1L6bpljVKXgyxSAFxNTJ-Aoz_kfOKaOiWrw&oe=6A2B40D3",
    text: "Embrace the fury of Sparta alongside Kratos in God Of War.",
    genre: "Hack and Slash",
    rating: 4.9,
    price: 3299,
    platforms: [
      "PlayStation 2",
      "PlayStation 3",
      "PlayStation 4",
      "PlayStation 5",
      "PC",
    ],
    description:
      "An epic, narrative-driven saga charting the blood-soaked journey of Kratos, the Ghost of Sparta, as he seeks vengeance against the Greek gods and later navigates the perilous realms of Norse mythology.",
  },
  {
    id: 107,
    title: "Assasins Creed",
    image:
      "https://scontent.fpnq7-9.fna.fbcdn.net/v/t39.30808-6/494479116_4275803769317780_8901609621433918953_n.jpg?stp=dst-jpg_tt6&cstp=mx1920x1080&ctp=s1920x1080&_nc_cat=102&ccb=1-7&_nc_sid=0b6b33&_nc_ohc=khDyyaYFCP4Q7kNvwFKRQ0F&_nc_oc=Adqt194g0cIC2G7RRAAB7QIJXux1fkEcOgaJd1KQY-iQ6UorjsTdHyJ4ld4I1oxbkPD-1xyMSCPUH1aW23SokG77&_nc_zt=23&_nc_ht=scontent.fpnq7-9.fna&_nc_gid=75lfSGF3HCiWicOlAKpSSQ&_nc_ss=782a8&oh=00_Af-d7WM-EfuMEuLqxrt7k7g7JQsfM-XpDgQ6J4kb-U_riw&oe=6A2B6024",
    text: "Explore rich, historical open worlds in the Assassins Creed franchise.",
    genre: "Stealth",
    rating: 4.5,
    price: 2499,
    platforms: [
      "PC",
      "PlayStation 3",
      "PlayStation 4",
      "PlayStation 5",
      "Xbox 360",
      "Xbox One",
      "Xbox Series X/S",
    ],
    description:
      "A massively popular open-world series centering on a millennia-old secret war between the Assassin Brotherhood, who fight for free will, and the Templar Order, who seek control, set across beautifully recreated historical eras.",
  },
  {
    id: 108,
    title: "Need For Speed: Hot Pursuit",
    image:
      "https://scontent.fpnq7-8.fna.fbcdn.net/v/t39.30808-6/496209495_4285176568380500_5868179528072850704_n.jpg?stp=dst-jpg_tt6&cstp=mx1920x1080&ctp=s1920x1080&_nc_cat=100&ccb=1-7&_nc_sid=0b6b33&_nc_ohc=mbG_yjXdEq0Q7kNvwENf7X0&_nc_oc=AdqhYZlIf26cDbKtJHmaqG4f_Ik6B4s51kgdgI3Ju1o0QQc5iW1UDHr1alZPZJCO5fg5bO2UadBzZnkFEEmP_idS&_nc_zt=23&_nc_ht=scontent.fpnq7-8.fna&_nc_gid=OlECbM17L8Vr6AK8VLuODA&_nc_ss=7b2a8&oh=00_Af8o-VzUDDwgLNotHXK1pzCXlX7RIn7Tkt0wBzUanqZJNQ&oe=6A2DE836",
    text: "Unleash a savage sense of speed both as an outlaw and a cop.",
    genre: "Racing",
    rating: 4.2,
    price: 1499,
    platforms: [
      "PlayStation 3",
      "Android",
      "Xbox 360",
      "Microsoft Windows",
      "Wii",
      "iOS",
      "Windows Phone",
      "webOS",
      "Java",
    ],
    description:
      "Feel the thrill of the chase and the rush of escape in Need for Speed™ Hot Pursuit Remastered. Unleash a savage sense of speed both as an outlaw and a cop in the world's hottest high-performance cars.",
  },
];

export const gamesCategories: Category[] = [
  {
    id: "rpg",
    name: "RPG",
    description: "Immerse yourself in epic role-playing adventures",
    color: "from-purple-600 to-blue-600",
    backgroundImage:
      "https://scontent.fpnq7-7.fna.fbcdn.net/v/t39.30808-6/541678251_804297732250685_4928180402584960456_n.jpg?stp=dst-jpg_tt6&cstp=mx736x414&ctp=s736x414&_nc_cat=106&ccb=1-7&_nc_sid=aa7b47&_nc_ohc=SId72a1p9JcQ7kNvwF6kfNe&_nc_oc=Adqai2VrR9QyqkC9GQLoActtlMP61PtXjB8eNMIctlTQfi5tuSMwbn_NvI_E63ZvPnILj7WpkymxCqFBGJDFUD81&_nc_zt=23&_nc_ht=scontent.fpnq7-7.fna&_nc_gid=1vZ82kzbMp_k7zZjumLsyw&_nc_ss=7b2a8&oh=00_Af_h5BR_eWB6W0OJ76-6Fy_XcrQZ8LcmQF-mjYwaoa7-kQ&oe=6A2DDF1F",
    games: [
      {
        id: 1,
        title: "Cyberpunk 2077",
        image: "https://picsum.photos/200/150?random=1",
        text: "Welcome to Night City, a megalopolis obsessed with power.",
        rating: 4.2,
        price: 59.99,
        discount: 20,
        genre: "RPG",
        description:
          "An open-world, action-adventure RPG set in the dark future of Night City, a dangerous megalopolis where power and modifications are everything.",
        platforms: ["PC", "PS5", "Xbox Series X", "PS4", "Xbox One"],
      },
      {
        id: 2,
        title: "The Witcher 3",
        image: "https://picsum.photos/200/150?random=2",
        text: "Become a professional monster hunter and embark on an epic journey.",
        rating: 4.8,
        price: 39.99,
        genre: "RPG",
        description:
          "A story-driven open world RPG set in a visually stunning dark fantasy universe where you play as Geralt of Rivia, a monster hunter for hire.",
        platforms: [
          "PC",
          "PS5",
          "Xbox Series X",
          "PS4",
          "Xbox One",
          "Nintendo Switch",
        ],
      },
      {
        id: 3,
        title: "Dragon Age: Inquisition",
        image: "https://picsum.photos/200/150?random=3",
        text: "Lead the Inquisition against the forces of chaos.",
        rating: 4.5,
        price: 29.99,
        genre: "RPG",
        description:
          "A massive action role-playing game where a cataclysmic event plunges the land of Thedas into turmoil, and you must lead the Inquisition to restore order.",
        platforms: ["PC", "PS4", "Xbox One", "PS3", "Xbox 360"],
      },
      {
        id: 4,
        title: "The Elder Scrolls V",
        image: "https://picsum.photos/200/150?random=4",
        text: "Epic fantasy reborn in a vast open world.",
        rating: 4.7,
        price: 19.99,
        genre: "RPG",
        description:
          "The definitive open-world fantasy epic where players can choose any path, play as the Dragonborn, and determine the fate of the empire.",
        platforms: [
          "PC",
          "PS5",
          "Xbox Series X",
          "PS4",
          "Xbox One",
          "Nintendo Switch",
        ],
      },
    ],
  },
  {
    id: "sandbox",
    name: "Sandbox",
    description: "Unleash your creativity in open worlds",
    color: "from-yellow-600 to-orange-500",
    backgroundImage:
      "https://scontent.fpnq7-7.fna.fbcdn.net/v/t1.6435-9/49102300_1947651862197978_2336654773882716160_n.jpg?stp=dst-jpg_tt6&cstp=mx2048x1152&ctp=s2048x1152&_nc_cat=106&ccb=1-7&_nc_sid=833d8c&_nc_ohc=pFZLGWKAkk8Q7kNvwG3aDml&_nc_oc=AdomgKPBD2beNRzF8zZA90j4OVKkg6NT-yPpCb5eHFXldm5WOhe3LuO2WB1bJ_Qu4o0tzzm3mu_eah3cj-4t8QEo&_nc_zt=23&_nc_ht=scontent.fpnq7-7.fna&_nc_gid=SImJClaJkUAoMumOuDJK3A&_nc_ss=7b2a8&oh=00_Af_L6R2fXyZfC0aMVHdFku1Yp3TzQ3DDeA3FIJN_7wVy_A&oe=6A4FABB3",
    games: [
      {
        id: 13,
        title: "Minecraft",
        image: "https://picsum.photos/200/150?random=13",
        text: "Explore infinite worlds and build everything from simple homes to castles.",
        rating: 4.7,
        price: 29.99,
        genre: "Sandbox",
        description:
          "A block-building sandbox game focused on exploration, survival, and limitless creativity in procedurally generated 3D environments.",
        platforms: [
          "PC",
          "Android",
          "iOS",
          "Xbox One",
          "PS4",
          "Nintendo Switch",
        ],
      },
      {
        id: 14,
        title: "Roblox",
        image: "https://picsum.photos/200/150?random=14",
        text: "The ultimate virtual universe that lets you create and share experiences.",
        rating: 3.9,
        price: 20,
        genre: "Sandbox",
        description:
          "An online game platform and storefront system that allows users to program games and play games created by other users.",
        platforms: ["PC", "Xbox One", "PS4", "iOS", "Android"],
      },
      {
        id: 15,
        title: "Terraria",
        image: "https://picsum.photos/200/150?random=15",
        text: "Dig, fight, explore, and build in a vast 2D world.",
        rating: 4.3,
        price: 9.99,
        genre: "Sandbox",
        description:
          "A 2D sandbox action-adventure game emphasizing crafting, building, boss fighting, and deep cavern exploration.",
        platforms: [
          "PC",
          "PS4",
          "Xbox One",
          "Nintendo Switch",
          "iOS",
          "Android",
        ],
      },
      {
        id: 16,
        title: "No Man's Sky",
        image: "https://picsum.photos/200/150?random=16",
        text: "A sci-fi game of exploration and survival in an infinite universe.",
        rating: 3.7,
        price: 39.99,
        genre: "Sandbox",
        description:
          "An ambitious space exploration sandbox game featuring a procedurally generated universe containing billions of unique planets to discover.",
        platforms: [
          "PC",
          "PS5",
          "Xbox Series X",
          "PS4",
          "Xbox One",
          "Nintendo Switch",
        ],
      },
    ],
  },
  {
    id: "sports",
    name: "Sports",
    description: "Experience realistic sports simulation",
    color: "from-green-600 to-teal-600",
    backgroundImage:
      "https://scontent.fpnq7-4.fna.fbcdn.net/v/t1.6435-9/122060849_2395305047432655_6301721277857317084_n.jpg?stp=dst-jpg_tt6&cstp=mx2048x1152&ctp=s2048x1152&_nc_cat=105&ccb=1-7&_nc_sid=833d8c&_nc_ohc=GUgiVMnjX0YQ7kNvwEcKQvs&_nc_oc=AdqkibYEgQ-oDmdhe8tf1VoEUumK-R5CkSQhtWWT2qTTuyzllDJHznij_VoWpluttO2xvYYzS0WKqXTTugUUEJLl&_nc_zt=23&_nc_ht=scontent.fpnq7-4.fna&_nc_gid=VqnyV6W2hbs-_63nQ9SEAg&_nc_ss=7b2a8&oh=00_Af-QJ_Ipt70LKHJBp0JGKOitjq5ptL7T3YxmG0a31NUwXg&oe=6A4F88C8",
    games: [
      {
        id: 9,
        title: "FIFA 24",
        image: "https://picsum.photos/200/150?random=9",
        text: "Experience the World's Game with unrivaled realism.",
        rating: 4.0,
        price: 69.99,
        discount: 15,
        genre: "Sports",
        description:
          "The premier football sports simulation engine delivering next-generation tactical engine dynamics and authentic player modeling.",
        platforms: [
          "PC",
          "PS5",
          "Xbox Series X",
          "PS4",
          "Xbox One",
          "Nintendo Switch",
        ],
      },
      {
        id: 10,
        title: "NBA 2K24",
        image: "https://picsum.photos/200/150?random=10",
        text: "Grab your squad and experience the past, present, and future of hoops.",
        rating: 4.2,
        price: 59.99,
        genre: "Sports",
        description:
          "An elite basketball simulation replicating professional NBA action with highly detailed franchise modes and dynamic online street courts.",
        platforms: [
          "PC",
          "PS5",
          "Xbox Series X",
          "PS4",
          "Xbox One",
          "Nintendo Switch",
        ],
      },
      {
        id: 11,
        title: "Madden NFL 24",
        image: "https://picsum.photos/200/150?random=11",
        text: "Lead your team to gridiron glory in Madden.",
        rating: 3.8,
        price: 59.99,
        genre: "Sports",
        description:
          "Replicate authentic American football matchups with enhanced collision systems and tactical playbook implementations.",
        platforms: ["PC", "PS5", "Xbox Series X", "PS4", "Xbox One"],
      },
      {
        id: 12,
        title: "F1 2023",
        image: "https://picsum.photos/200/150?random=12",
        text: "Be the last to brake in the official Formula One game.",
        rating: 4.1,
        price: 49.99,
        genre: "Sports",
        description:
          "The official racing simulation of the FIA Formula One World Championship featuring all real-world drivers, teams, and technical tracks.",
        platforms: ["PC", "PS5", "Xbox Series X", "PS4", "Xbox One"],
      },
    ],
  },
  {
    id: "fps",
    name: "FPS",
    description: "Fast-paced first-person shooter action",
    color: "from-red-600 to-orange-600",
    backgroundImage:
      "https://scontent.fpnq7-10.fna.fbcdn.net/v/t39.30808-6/306163056_395896469359663_7079360747547170045_n.jpg?stp=dst-jpg_tt6&cstp=mx1920x1080&ctp=s1920x1080&_nc_cat=109&ccb=1-7&_nc_sid=6ee11a&_nc_ohc=hiK-M0_B7zkQ7kNvwFMc8vU&_nc_oc=AdomJxW3UxBN3VZHVzvHV716itzOvDfpWPIFUTnUumzc4Wpitu8x-677_Q5LHO3dBs9M-qTbkFbvPyvdZK_ueIbL&_nc_zt=23&_nc_ht=scontent.fpnq7-10.fna&_nc_gid=FhUjmVSvzZm3rPKT_fsXYQ&_nc_ss=7b2a8&oh=00_Af_lCQr7GX6GZE2I07rSnR_V1tFSEU8qVJoMkl9qB21hCw&oe=6A2E0853",
    games: [
      {
        id: 5,
        title: "Call of Duty: MWIII",
        image: "https://picsum.photos/200/150?random=5",
        text: "Adapt or die in a fight against the ultimate threat.",
        rating: 4.1,
        price: 69.99,
        genre: "FPS",
        description:
          "A fast-paced military multiplayer and blockbuster cinematic first-person military campaign pushing modern infantry combat bounds.",
        platforms: ["PC", "PS5", "Xbox Series X", "PS4", "Xbox One"],
      },
      {
        id: 6,
        title: "Counter-Strike 2",
        image: "https://picsum.photos/200/150?random=6",
        text: "The premier competitive tactical squad game.",
        rating: 4.3,
        price: 20,
        genre: "FPS",
        description:
          "A tactical five-versus-five team-based shooter focusing on mechanical aim skill, precise smoke setups, and map macro strategy.",
        platforms: ["PC"],
      },
      {
        id: 7,
        title: "Apex Legends",
        image: "https://picsum.photos/200/150?random=7",
        text: "Conquer with character in a free-to-play battle royale shooter.",
        rating: 4.0,
        price: 20,
        genre: "FPS",
        description:
          "A hero-driven high-mobility battle royale where squads match unique futuristic tactical toolsets across sprawling dynamic battlefields.",
        platforms: [
          "PC",
          "PS4",
          "Xbox One",
          "Nintendo Switch",
          "PS5",
          "Xbox Series X",
        ],
      },
      {
        id: 8,
        title: "Valorant",
        image: "https://picsum.photos/200/150?random=8",
        text: "A character-based 5v5 tactical shooter where gunplay meets utility.",
        rating: 4.4,
        price: 20,
        genre: "FPS",
        description:
          "A competitive mechanical shooter blending hyper-accurate hitscan mechanics with unique fantasy hero ability utility packages.",
        platforms: ["PC", "PS5", "Xbox Series X"],
      },
    ],
  },
  {
    id: "action-adventure",
    name: "Action-Adventure",
    description:
      "Thrilling stories combined with intense combat and exploration",
    color: "from-sky-600 to-indigo-700",
    backgroundImage:
      "https://scontent.fpnq7-1.fna.fbcdn.net/v/t1.6435-9/48249833_1935754300054401_116974108616425472_n.jpg?stp=dst-jpg_tt6&cstp=mx2048x1280&ctp=s2048x1280&_nc_cat=101&ccb=1-7&_nc_sid=833d8c&_nc_ohc=YuBgyKTJ1eQQ7kNvwF3dQZb&_nc_oc=Adq2MeWkmA_2VclCn60z-WXnthH4IqM39nYVV6meDCw7jGFv_0jk2Vpcymisp3uQ9Rd-MEsWBROfzFv_rNFQmDZx&_nc_zt=23&_nc_ht=scontent.fpnq7-1.fna&_nc_gid=21WLLZWG63MgVt9KAmEfgQ&_nc_ss=7b2a8&oh=00_Af_jDh8y-bmxAseRUxNPgQVV-7NGscvHONa00bGNLlupLQ&oe=6A4FA1A6",
    games: [
      {
        id: 21,
        title: "Elden Ring",
        image: "https://picsum.photos/200/150?random=21",
        text: "Rise, Tarnished, and be guided by grace to brandish the Elden Ring.",
        rating: 4.9,
        price: 59.99,
        genre: "Action-Adventure",
        description:
          "An sprawling open-world action masterpiece showcasing rigorous high-stakes swordplay within an layered dark fantasy ecosystem.",
        platforms: ["PC", "PS5", "Xbox Series X", "PS4", "Xbox One"],
      },
      {
        id: 22,
        title: "God of War Ragnarök",
        image: "https://picsum.photos/200/150?random=22",
        text: "Embark on an epic and heartfelt journey as Kratos and Atreus struggle with holding on.",
        rating: 4.8,
        price: 69.99,
        discount: 10,
        genre: "Action-Adventure",
        description:
          "Follow the intense emotional mythic journey of Kratos and Atreus as they navigate ancient prophecy and Norse apocalyptic horizons.",
        platforms: ["PS5", "PS4", "PC"],
      },
      {
        id: 23,
        title: "Red Dead Redemption 2",
        image: "https://picsum.photos/200/150?random=23",
        text: "An epic tale of life in America's unforgiving heartland.",
        rating: 4.9,
        price: 59.99,
        discount: 60,
        genre: "Action-Adventure",
        description:
          "A deeply interactive open-world western tracking Arthur Morgan and the infamous Van der Linde gang as they run from the dawn of industrialization.",
        platforms: ["PC", "PS4", "Xbox One"],
      },
      {
        id: 24,
        title: "Grand Theft Auto V",
        image: "https://picsum.photos/200/150?random=24",
        text: "Explore the vast world of Los Santos and Blaine County.",
        rating: 4.7,
        price: 29.99,
        genre: "Action-Adventure",
        description:
          "A satirical open-world crime thriller featuring interwoven paths of three criminals pulling off major multi-stage heist sequences.",
        platforms: [
          "PC",
          "PS5",
          "Xbox Series X",
          "PS4",
          "Xbox One",
          "PS3",
          "Xbox 360",
        ],
      },
    ],
  },
  {
    id: "fighting",
    name: "Fighting",
    description:
      "Go head-to-head in precise, martial arts-driven competitive brawls",
    color: "from-rose-700 to-orange-600",
    backgroundImage:
      "https://scontent.fpnq7-9.fna.fbcdn.net/v/t39.30808-6/495740684_3008250769352391_3077427185784118430_n.jpg?stp=dst-jpg_tt6&cstp=mx1920x1080&ctp=s1920x1080&_nc_cat=102&ccb=1-7&_nc_sid=536f4a&_nc_ohc=VXylwiBK4Q0Q7kNvwGjpQBo&_nc_oc=AdqZfn_hN3Hk6LuDL9WYZ67gZvG-CYESDAuZEyy5aMu9vWg8LOaUdF-16T-P47YZofaTY0kvibP4-9i03ocihldS&_nc_zt=23&_nc_ht=scontent.fpnq7-9.fna&_nc_gid=ApDjYHSiqLLVj5jw2odGPg&_nc_ss=7b2a8&oh=00_Af-pGEcbTke-JuAg1pUVGWMB8lzF9poVe9BImiVQeCgpgw&oe=6A2E01DD",
    games: [
      {
        id: 37,
        title: "Street Fighter 6",
        image: "https://picsum.photos/200/150?random=37",
        text: "The evolving fighting arena built for casual and pro warriors alike.",
        rating: 4.6,
        price: 59.99,
        genre: "Fighting",
        description:
          "Capcom's elite fighting evolution integrating fluid command link systems alongside robust neutral tactical control spacing mechanics.",
        platforms: ["PC", "PS5", "PS4", "Xbox Series X"],
      },
      {
        id: 38,
        title: "Mortal Kombat 1",
        image: "https://picsum.photos/200/150?random=38",
        text: "Discover a reborn Mortal Kombat Universe created by the Fire God Liu Kang.",
        rating: 4.2,
        price: 69.99,
        genre: "Fighting",
        description:
          "A complete structural combat reset featuring dramatic Kameo partner combat dynamics alongside iconic bone-crushing finish maneuvers.",
        platforms: ["PC", "PS5", "Xbox Series X", "Nintendo Switch"],
      },
      {
        id: 39,
        title: "Tekken 8",
        image: "https://picsum.photos/200/150?random=39",
        text: "Fist Meets Fate in the ultimate next-generation fighting tournament.",
        rating: 4.7,
        price: 69.99,
        genre: "Fighting",
        description:
          "The peak implementation of intense 3D arena spatial fighting mechanics emphasizing tactical spatial aggression and robust combo architecture.",
        platforms: ["PC", "PS5", "Xbox Series X"],
      },
      {
        id: 40,
        title: "Super Smash Bros. Ultimate",
        image: "https://picsum.photos/200/150?random=40",
        text: "Legendary game worlds and characters collide in the ultimate showdown.",
        rating: 4.8,
        price: 59.99,
        genre: "Fighting",
        description:
          "The ultimate historic celebration crossover brawler matching vast dynamic rosters on custom changing geographic platform sets.",
        platforms: ["Nintendo Switch"],
      },
    ],
  },
  {
    id: "horror",
    name: "Horror",
    description: "Face your deepest fears in terrifying survival experiences",
    color: "from-zinc-900 to-red-950",
    backgroundImage:
      "https://scontent.fpnq7-4.fna.fbcdn.net/v/t1.6435-9/51795563_1971043259858838_6754995215913713664_n.jpg?stp=dst-jpg_tt6&cstp=mx1920x1080&ctp=s1920x1080&_nc_cat=110&ccb=1-7&_nc_sid=833d8c&_nc_ohc=kGhfw1W-5gYQ7kNvwHViCnu&_nc_oc=AdqctT03sIzmxua3uMa1sJgGTmmddV17KsSRfrGDBLHkmjflMohFzdWKxBGelwqR8aBGtw-JbyUP5FjXUEdwQa1Z&_nc_zt=23&_nc_ht=scontent.fpnq7-4.fna&_nc_gid=D_ihWucW5SiJuqHWSvq68w&_nc_ss=7b2a8&oh=00_Af_2LPNYY9Mb_JE0lKQHpwNP8qFjZ7jhNJp3PwKiIEK3_g&oe=6A4F9181",
    games: [
      {
        id: 29,
        title: "Resident Evil 4 (Remake)",
        image: "https://picsum.photos/200/150?random=29",
        text: "Survival is just the beginning in this reimagined horror masterpiece.",
        rating: 4.8,
        price: 59.99,
        genre: "Horror",
        description:
          "An intensive third-person overhaul matching survival biological anxiety with tight defensive ammunition micromanagement loop cycles.",
        platforms: ["PC", "PS5", "Xbox Series X", "PS4"],
      },
      {
        id: 30,
        title: "Dead by Daylight",
        image: "https://picsum.photos/200/150?random=30",
        text: "Death is not an escape in this asymmetrical multiplayer horror game.",
        rating: 4.1,
        price: 19.99,
        genre: "Horror",
        description:
          "An intense multi-perspective 4v1 escape contest matching vulnerable ground survivors against a single relentless specialized serial tracking monster.",
        platforms: [
          "PC",
          "PS4",
          "Xbox One",
          "Nintendo Switch",
          "PS5",
          "Xbox Series X",
        ],
      },
      {
        id: 31,
        title: "Phasmophobia",
        image: "https://picsum.photos/200/150?random=31",
        text: "Use paranormal investigation equipment to gather evidence of ghost activity.",
        rating: 4.5,
        price: 13.99,
        genre: "Horror",
        description:
          "A cooperative audio-spatial investigation puzzle testing precise hardware deployment loops against highly responsive, invisible dynamic entities.",
        platforms: ["PC", "PS5", "Xbox Series X/S"],
      },
      {
        id: 32,
        title: "Outlast 2",
        image: "https://picsum.photos/200/150?random=32",
        text: "A twisted journey into the depths of the human mind and its dark secrets.",
        rating: 4.0,
        price: 29.99,
        discount: 80,
        genre: "Horror",
        description:
          "A helpless first-person descent removing combat capacity entirely, forcing immediate flight dynamics using limited camera battery illumination frameworks.",
        platforms: ["PC", "PS4", "Xbox One", "Nintendo Switch"],
      },
    ],
  },
  {
    id: "racing",
    name: "Racing",
    description: "Burn rubber and master high-speed vehicle control",
    color: "from-emerald-600 to-cyan-600",
    backgroundImage:
      "https://scontent.fpnq7-4.fna.fbcdn.net/v/t1.6435-9/47685442_1936166116679886_7110898479760670720_n.jpg?stp=dst-jpg_tt6&cstp=mx2048x1280&ctp=s2048x1280&_nc_cat=105&ccb=1-7&_nc_sid=833d8c&_nc_ohc=CYk7wGTSKPkQ7kNvwHDlfr-&_nc_oc=AdqiJNbml8bmLEVelXEWblPV9XEw6iwp9on5u6vln_bksExs7RMV0IwPRtbmOXJq5Ux0BQZwTIxxbjqQsXEdOsOU&_nc_zt=23&_nc_ht=scontent.fpnq7-4.fna&_nc_gid=C3ORMdZLYIq3s4QKi2bAEw&_nc_ss=7b2a8&oh=00_Af_RUl-ykqjg4NdkmkGoJqeqdUT4YXQxS24uxWfhI-H0fg&oe=6A4FA7DC",
    games: [
      {
        id: 33,
        title: "Forza Horizon 5",
        image: "https://picsum.photos/200/150?random=33",
        text: "Your ultimate Horizon Adventure awaits! Explore vibrant open worlds.",
        rating: 4.7,
        price: 59.99,
        genre: "Racing",
        description:
          "An exquisite open world automotive experience mapping highly meticulous physics across gorgeous, changing atmospheric terrains.",
        platforms: ["PC", "Xbox Series X", "Xbox One"],
      },
      {
        id: 34,
        title: "Need for Speed Unbound",
        image: "https://picsum.photos/200/150?random=34",
        text: "Race against time, outsmart the cops, and take on weekly qualifiers.",
        rating: 3.9,
        price: 69.99,
        discount: 40,
        genre: "Racing",
        description:
          "An arcade racing thriller matching cell-shaded visual flourishes with technical illegal drift and high stakes metropolitan police evasion metrics.",
        platforms: ["PC", "PS5", "Xbox Series X"],
      },
      {
        id: 35,
        title: "Gran Turismo 7",
        image: "https://picsum.photos/200/150?random=35",
        text: "The Real Driving Simulator. Find your line.",
        rating: 4.5,
        price: 69.99,
        genre: "Racing",
        description:
          "The peak implementation of absolute track simulation precision covering historic vehicle conservation catalogs and hyper-authentic track tire traction dynamics.",
        platforms: ["PS5", "PS4"],
      },
      {
        id: 36,
        title: "Assetto Corsa Competizione",
        image: "https://picsum.photos/200/150?random=36",
        text: "The official GT World Challenge videogame.",
        rating: 4.4,
        price: 39.99,
        genre: "Racing",
        description:
          "An elite commercial motorsport engineering simulation providing pristine tire fidelity modeling, exact wheel inputs, and specialized GT circuit fidelity.",
        platforms: ["PC", "PS5", "Xbox Series X", "PS4", "Xbox One"],
      },
    ],
  },
  {
    id: "strategy",
    name: "Strategy",
    description: "Outwit your opponents with tactical planning and execution",
    color: "from-amber-700 to-yellow-600",
    backgroundImage:
      "https://scontent.fpnq7-6.fna.fbcdn.net/v/t1.6435-9/48363673_1936164836680014_8102460021561884672_n.jpg?stp=dst-jpg_tt6&cstp=mx2048x1152&ctp=s2048x1152&_nc_cat=111&ccb=1-7&_nc_sid=833d8c&_nc_ohc=fFpUMFBdLGgQ7kNvwH0rGxr&_nc_oc=Adp8TwTivEmkfKobY5qeuhb4-d5LHO2WbkyKhHKb1jkB_FslvOSvoEKOzjKHLKZliaZptxRIiXkEB1mpmYiYAH_R&_nc_zt=23&_nc_ht=scontent.fpnq7-6.fna&_nc_gid=9MGjBkHbP4zh9oZmcZZB5A&_nc_ss=7b2a8&oh=00_Af-3Iw-I0yolGLe-zHL_ukz_kkm_rYaOB-OOxik6yR-0cw&oe=6A4F9A8E",
    games: [
      {
        id: 25,
        title: "Civilization VI",
        image: "https://picsum.photos/200/150?random=25",
        text: "Build an empire to stand the test of time.",
        rating: 4.4,
        price: 59.99,
        discount: 75,
        genre: "Strategy",
        description:
          "A turn-based strategy game in which you attempt to build an empire to stand the test of time, expanding your empire across the map.",
        platforms: ["PC", "PS4", "Xbox One", "Nintendo Switch", "iOS"],
      },
      {
        id: 26,
        title: "Age of Empires IV",
        image: "https://picsum.photos/200/150?random=26",
        text: "Epic historical battles await.",
        rating: 4.3,
        price: 39.99,
        genre: "Strategy",
        description:
          "Puts you at the center of epic historical battles that shaped the modern world in a real-time strategy experience.",
        platforms: ["PC", "Xbox Series X", "Xbox One"],
      },
      {
        id: 27,
        title: "StarCraft II",
        image: "https://picsum.photos/200/150?random=27",
        text: "Wage real-time sci-fi war.",
        rating: 4.6,
        price: 20,
        genre: "Strategy",
        description:
          "Wage real-time sci-fi war across the galaxy using three uniquely powerful races.",
        platforms: ["PC"],
      },
      {
        id: 28,
        title: "Total War: Warhammer III",
        image: "https://picsum.photos/200/150?random=28",
        text: "Rally your forces and step into the Realm of Chaos.",
        rating: 4.1,
        price: 59.99,
        genre: "Strategy",
        description:
          "A brilliant mix of granular, turn-based kingdom management combined with intense real-time strategic sandbox combat controls.",
        platforms: ["PC", "macOS", "Linux"],
      },
    ],
  },
];

export const allGames: GameDetail[] = [
  {
    id: 1,
    title: "Cyberpunk 2077",
    image: "https://wallpapercave.com/wp/wp6823992.jpg",
    text: "Welcome to Night City, a megalopolis obsessed with power.",
    rating: 4.2,
    price: 2999,
    discount: 20,
    genre: "RPG",
    description:
      "An open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour, and body modification.",
    platforms: ["PC", "PS5", "Xbox Series X"],
  },
  {
    id: 2,
    title: "The Witcher 3",
    image: "https://wallpapercave.com/wp/wp1854635.jpg",
    text: "Become a professional monster hunter and embark on an epic journey.",
    rating: 4.8,
    price: 1799,
    genre: "RPG",
    description:
      "A story-driven, next-generation open-world role-playing game set in a visually stunning fantasy universe.",
    platforms: ["PC", "PS5", "Xbox Series X", "Nintendo Switch"],
  },
  {
    id: 3,
    title: "Dragon Age: Inquisition",
    image: "https://wallpapercave.com/wp/wp2179404.jpg",
    text: "Lead the Inquisition against the forces of chaos.",
    rating: 4.5,
    price: 2499,
    genre: "RPG",
    description:
      "Become the Inquisitor and lead a team of legendary heroes to save a fractured world from the brink of destruction.",
    platforms: ["PC", "PS4", "Xbox One"],
  },
  {
    id: 4,
    title: "The Elder Scrolls V",
    image: "https://wallpapercave.com/wp/wp72199.jpg",
    text: "Epic fantasy reborn in a vast open world.",
    rating: 4.7,
    price: 1799,
    genre: "RPG",
    description:
      "Epic fantasy reimagined, allowing you to play any type of character you can imagine and explore a vast open world.",
    platforms: ["PC", "PS5", "Xbox Series X", "Nintendo Switch"],
  },
  {
    id: 13,
    title: "Minecraft",
    image: "https://wallpapercave.com/wp/wp2777682.jpg",
    text: "Explore infinite worlds and build everything from simple homes to castles.",
    rating: 4.7,
    price: 1999,
    genre: "Sandbox",
    description:
      "Explore infinite worlds and build everything from the simplest of homes to the grandest of castles.",
    platforms: ["PC", "PS4", "Xbox One", "Nintendo Switch", "iOS", "Android"],
  },
  {
    id: 15,
    title: "Terraria",
    image: "https://wallpapercave.com/wp/wp2610586.jpg",
    text: "Dig, fight, explore, and build in a vast 2D world.",
    rating: 4.3,
    price: 479,
    genre: "Sandbox",
    description:
      "Dig, fight, explore, and build in an action-packed sandbox adventure where the world is your canvas.",
    platforms: ["PC", "PS4", "Xbox One", "Nintendo Switch", "iOS", "Android"],
  },
  {
    id: 16,
    title: "No Man's Sky",
    image: "https://wallpapercave.com/wp/wp1851426.jpg",
    text: "A sci-fi game of exploration and survival in an infinite universe.",
    rating: 3.7,
    price: 2400,
    genre: "Sandbox",
    description:
      "A sci-fi exploration game set in an infinite procedurally generated universe full of unique planets and lifeforms.",
    platforms: ["PC", "PS5", "Xbox Series X", "Nintendo Switch"],
  },
  {
    id: 9,
    title: "FIFA 24",
    image: "https://wallpapercave.com/wp/wp12593837.jpg",
    text: "Experience the World's Game with unrivaled realism.",
    rating: 4.0,
    price: 3499,
    discount: 15,
    genre: "Sports",
    description:
      "Experience the world's game with unparalleled realism, featuring the biggest tournaments, leagues, and players.",
    platforms: ["PC", "PS5", "Xbox Series X", "Nintendo Switch"],
  },
  {
    id: 10,
    title: "NBA 2K24",
    image: "https://wallpapercave.com/wp/wp12585965.jpg",
    text: "Grab your squad and experience the past, present, and future of hoops.",
    rating: 4.2,
    price: 3299,
    genre: "Sports",
    description:
      "Grab your squad and experience the past, present, and future of hoops culture with pure, authentic basketball action.",
    platforms: ["PC", "PS5", "Xbox Series X", "Nintendo Switch"],
  },
  {
    id: 11,
    title: "Madden NFL 24",
    image: "https://wallpapercave.com/wp/wp12699956.jpg",
    text: "Lead your team to gridiron glory in Madden.",
    rating: 3.8,
    price: 3499,
    genre: "Sports",
    description:
      "Lead your team to a Super Bowl victory with enhanced control, realistic collisions, and deeper gameplay systems.",
    platforms: ["PC", "PS5", "Xbox Series X"],
  },
  {
    id: 12,
    title: "F1 2023",
    image: "https://wallpapercave.com/wp/wp9896704.jpg",
    text: "Be the last to brake in the official Formula One game.",
    rating: 4.1,
    price: 2999,
    genre: "Sports",
    description:
      "The official videogame of the FIA Formula One World Championship, featuring high-speed racing drama and tactics.",
    platforms: ["PC", "PS5", "Xbox Series X"],
  },
  {
    id: 5,
    title: "Call of Duty: MWIII",
    image: "https://wallpapercave.com/wp/wp13002741.jpg",
    text: "Adapt or die in a fight against the ultimate threat.",
    rating: 4.1,
    price: 5599,
    genre: "FPS",
    description:
      "Adapt or die in a fight against the ultimate threat, featuring iconic multiplayer maps and a cinematic campaign.",
    platforms: ["PC", "PS5", "Xbox Series X"],
  },
  {
    id: 21,
    title: "Elden Ring",
    image: "https://wallpapercave.com/wp/wp14808661.webp",
    text: "Rise, Tarnished, and be guided by grace to brandish the Elden Ring.",
    rating: 4.9,
    price: 3599,
    genre: "Action-Adventure",
    description:
      "Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring in a massive dark fantasy world.",
    platforms: ["PC", "PS5", "Xbox Series X"],
  },
  {
    id: 22,
    title: "God of War Ragnarök",
    image: "https://wallpapercave.com/wp/wp11690916.jpg",
    text: "Embark on an epic and heartfelt journey as Kratos and Atreus struggle with holding on.",
    rating: 4.8,
    price: 3999,
    discount: 10,
    genre: "Action-Adventure",
    description:
      "Join Kratos and Atreus on a mythic journey for answers and allies before Ragnarök arrives.",
    platforms: ["PC", "PS4", "PS5"],
  },
  {
    id: 23,
    title: "Red Dead Redemption 2",
    image: "https://wallpapercave.com/wp/wp3770429.png",
    text: "An epic tale of life in America's unforgiving heartland.",
    rating: 4.9,
    price: 3199,
    discount: 60,
    genre: "Action-Adventure",
    description:
      "An epic tale of life in America’s unforgiving heartland at the dawn of the modern age.",
    platforms: ["PC", "PS4", "Xbox One"],
  },
  {
    id: 24,
    title: "Grand Theft Auto V",
    image: "https://wallpapercave.com/wp/wp1809630.jpg",
    text: "Explore the vast world of Los Santos and Blaine County.",
    rating: 4.7,
    price: 2321,
    genre: "Action-Adventure",
    description:
      "When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled, they must pull off heists to survive.",
    platforms: ["PC", "PS5", "Xbox Series X"],
  },
  {
    id: 37,
    title: "Street Fighter 6",
    image: "https://wallpapercave.com/wp/wp12751223.jpg",
    text: "The evolving fighting arena built for casual and pro warriors alike.",
    rating: 4.6,
    price: 3999,
    genre: "Fighting",
    description:
      "Powered by a proprietary engine, experience a new era of fighting games with evolved mechanics and vibrant visuals.",
    platforms: ["PC", "PS5", "Xbox Series X"],
  },
  {
    id: 38,
    title: "Mortal Kombat 1",
    image: "https://wallpapercave.com/wp/wp13016862.png",
    text: "Discover a reborn Mortal Kombat Universe created by the Fire God Liu Kang.",
    rating: 4.2,
    price: 4499,
    genre: "Fighting",
    description:
      "Discover a reborn Mortal Kombat Universe created by the Fire God Liu Kang, featuring gory fatalities and new fight styles.",
    platforms: ["PC", "PS5", "Xbox Series X", "Nintendo Switch"],
  },
  {
    id: 39,
    title: "Tekken 8",
    image: "https://wallpapercave.com/wp/wp12826870.jpg",
    text: "Fist Meets Fate in the ultimate next-generation fighting tournament.",
    rating: 4.7,
    price: 4399,
    genre: "Fighting",
    description:
      "Fist Meets Fate in this next-generation installment of the historic fighting franchise, powered by highly aggressive gameplay mechanics.",
    platforms: ["PC", "PS5", "Xbox Series X"],
  },
  {
    id: 40,
    title: "Super Smash Bros. Ultimate",
    image: "https://wallpapercave.com/wp/wp3755804.jpg",
    text: "Legendary game worlds and characters collide in the ultimate showdown.",
    rating: 4.8,
    price: 4999,
    genre: "Fighting",
    description:
      "Legendary game worlds and fighters collide in the ultimate showdown, where the goal is to launch rivals off the stage.",
    platforms: ["Nintendo Switch"],
  },
  {
    id: 29,
    title: "Resident Evil 4 (Remake)",
    image: "https://wallpapercave.com/wp/wp12116688.jpg",
    text: "Survival is just the beginning in this reimagined horror masterpiece.",
    rating: 4.8,
    price: 3599,
    genre: "Horror",
    description:
      "Survival is just the beginning in this fully reimagined survival-horror masterpiece featuring updated modern combat.",
    platforms: ["PC", "PS5", "Xbox Series X"],
  },
  {
    id: 30,
    title: "Dead by Daylight",
    image: "https://wallpapercave.com/wp/wp2222211.jpg",
    text: "Death is not an escape in this asymmetrical multiplayer horror game.",
    rating: 4.1,
    price: 999,
    genre: "Horror",
    description:
      "A multiplayer 4v1 horror game where one player takes on the role of the savage Killer, and the other four play as Survivors.",
    platforms: ["PC", "PS5", "Xbox Series X", "Nintendo Switch"],
  },
  {
    id: 31,
    title: "Phasmophobia",
    image: "https://wallpapercave.com/wp/wp7775365.jpg",
    text: "Use paranormal investigation equipment to gather evidence of ghost activity.",
    rating: 4.5,
    price: 690,
    genre: "Horror",
    description:
      "A 4-player online co-op psychological horror where you and your team of paranormal investigators enter haunted locations.",
    platforms: ["PC", "PS5", "Xbox Series X"],
  },
  {
    id: 32,
    title: "Outlast 2",
    image: "https://wallpapercave.com/wp/wp2329691.jpg",
    text: "A twisted journey into the depths of the human mind and its dark secrets.",
    rating: 4.0,
    price: 1300,
    discount: 80,
    genre: "Horror",
    description:
      "Navigate a twisted, terrifying journey through a secretive desert cult community armed only with a video camera.",
    platforms: ["PC", "PS4", "Xbox One", "Nintendo Switch"],
  },
  {
    id: 33,
    title: "Forza Horizon 5",
    image: "https://wallpapercave.com/wp/wp12405465.jpg",
    text: "Your ultimate Horizon Adventure awaits! Explore vibrant open worlds.",
    rating: 4.7,
    price: 3499,
    genre: "Racing",
    description:
      "Lead breathtaking expeditions across the vibrant and ever-evolving open world landscapes of Mexico in hundreds of world-class cars.",
    platforms: ["PC", "Xbox Series X", "Xbox One"],
  },
  {
    id: 34,
    title: "Need for Speed Unbound",
    image: "https://wallpapercave.com/wp/wp11595581.png",
    text: "Race against time, outsmart the cops, and take on weekly qualifiers.",
    rating: 3.9,
    price: 3499,
    discount: 40,
    genre: "Racing",
    description:
      "Race against time, outsmart the cops, and take on weekly qualifiers to reach The Grand, Lakeshore's ultimate street racing challenge.",
    platforms: ["PC", "PS5", "Xbox Series X"],
  },
  {
    id: 35,
    title: "Gran Turismo 7",
    image: "https://wallpapercave.com/wp/wp7722224.jpg",
    text: "The Real Driving Simulator. Find your line.",
    rating: 4.5,
    price: 4999,
    genre: "Racing",
    description:
      "The ultimate driving simulator brings together the best features of the real-world racing franchise with deep customization.",
    platforms: ["PS4", "PS5"],
  },
  {
    id: 36,
    title: "Assetto Corsa Competizione",
    image: "https://wallpapercave.com/wp/wp13905088.jpg",
    text: "The official GT World Challenge videogame.",
    rating: 4.4,
    price: 1999,
    genre: "Racing",
    description:
      "The official GT World Challenge videogame allows you to experience the real atmosphere of the GT3 championship.",
    platforms: ["PC", "PS5", "Xbox Series X"],
  },
  {
    id: 25,
    title: "Civilization VI",
    image: "https://wallpapercave.com/wp/wp3805937.jpg",
    text: "Build an empire to stand the test of time.",
    rating: 4.4,
    price: 2499,
    discount: 75,
    genre: "Strategy",
    description:
      "A turn-based strategy game in which you attempt to build an empire to stand the test of time, expanding your empire across the map.",
    platforms: ["PC", "PS4", "Xbox One", "Nintendo Switch", "iOS"],
  },
  {
    id: 26,
    title: "Age of Empires IV",
    image: "https://wallpapercave.com/wp/wp9682100.jpg",
    text: "Epic historical battles await.",
    rating: 4.3,
    price: 2399,
    genre: "Strategy",
    description:
      "Puts you at the center of epic historical battles that shaped the modern world in a real-time strategy experience.",
    platforms: ["PC", "Xbox Series X", "Xbox One"],
  },
  {
    id: 28,
    title: "Total War: Warhammer III",
    image: "https://wallpapercave.com/wp/wp8532667.jpg",
    text: "Rally your forces and step into the Realm of Chaos.",
    rating: 4.1,
    price: 3399,
    genre: "Strategy",
    description:
      "Rally your forces and step into the Realm of Chaos, a dimension of mind-bending horror where the world's fate is decided.",
    platforms: ["PC"],
  },
];

export const GOTYList: GOTYGameDetail[] = [
  {
    id: 2025,
    title: "Clair Obscur: Expedition 33",
    developer: "Sandfall Interactive",
    images: [
      "https://wallpapercave.com/wp/wp15037158.webp",
      "https://wallpapercave.com/wp/wp15037159.webp",
      "https://wallpapercave.com/wp/wp15037157.webp",
      "https://wallpapercave.com/wp/wp15037156.webp",
      "https://wallpapercave.com/wp/wp15037155.webp",
    ],
    year: 2025,
    awards: ["Game of the Year", "Best RPG", "Best Art Direction"],
    description:
      "A turn-based RPG featuring real-time mechanics where you lead the Expeditionary force to destroy the Paintress before she paints death upon the world.",
    rating: 4.8,
    isWinner: true,
    category: "Game of the Year",
    platforms: ["PC", "PS5", "Xbox Series X"],
    recommendedSystemRequirements: {
      os: "Windows 11 (64-bit)",
      processor: "Intel Core i7-12700K / AMD Ryzen 7 7700X",
      memory: "16 GB RAM",
      graphics: "NVIDIA GeForce RTX 4070 / AMD Radeon RX 7800 XT",
      vram: "12 GB",
      directX: "Version 12",
      storage: "90 GB available space (SSD required)",
    },
  },
  {
    id: 2024,
    title: "Astro Bot",
    developer: "Team Asobi",
    images: [
      "https://wallpapercave.com/wp/wp14428873.jpg",
      "https://wallpapercave.com/wp/wp8415018.jpg",
      "https://wallpapercave.com/wp/wp14428871.jpg",
      "https://wallpapercave.com/wp/wp12002657.jpg",
      "https://wallpapercave.com/wp/wp8395512.jpg",
    ],
    year: 2024,
    awards: ["Game of the Year", "Best Game Direction", "Best Family Game"],
    description:
      "An celebration of PlayStation history wrapped inside a masterpiece of a 3D platformer featuring creative level designs and deep DualSense integration.",
    rating: 4.9,
    isWinner: true,
    category: "Game of the Year",
    platforms: ["PS5"],
    recommendedSystemRequirements: {
      os: "N/A (PlayStation 5 Exclusive)",
      processor: "N/A",
      memory: "N/A",
      graphics: "N/A",
      vram: "N/A",
      directX: "N/A",
      storage: "66 GB available space (Internal SSD)",
    },
  },
  {
    id: 2023,
    title: "Baldur's Gate 3",
    developer: "Larian Studios",
    images: [
      "https://wallpapercave.com/wp/wp6376877.jpg",
      "https://wallpapercave.com/wp/wp7527718.jpg",
      "https://wallpapercave.com/wp/wp8231508.jpg",
      "https://wallpapercave.com/wp/wp7527536.jpg",
      "https://wallpapercave.com/wp/wp8231682.jpg",
    ],
    year: 2023,
    awards: [
      "Game of the Year",
      "Best RPG",
      "Best Narrative",
      "Player's Voice",
    ],
    description:
      "An expansive, player-choice-driven RPG set in the universe of Dungeons & Dragons, boasting deep tactical turn-based combat and rich storytelling.",
    rating: 4.9,
    isWinner: true,
    category: "Game of the Year",
    platforms: ["PC", "PS5", "Xbox Series X"],
    recommendedSystemRequirements: {
      os: "Windows 10 / 11 (64-bit)",
      processor: "Intel Core i7-8700K / AMD Ryzen 5 3600X",
      memory: "16 GB RAM",
      graphics: "NVIDIA GeForce RTX 2060 Super / AMD Radeon RX 5700 XT",
      vram: "8 GB",
      directX: "Version 11",
      storage: "150 GB available space (SSD required)",
    },
  },
  {
    id: 2022,
    title: "Elden Ring",
    developer: "FromSoftware",
    images: [
      "https://wallpapercave.com/wp/wp14808661.webp",
      "https://wallpapercave.com/wp/wp13489035.jpg",
      "https://wallpapercave.com/wp/wp14808666.webp",
      "https://wallpapercave.com/wp/wp14035067.webp",
      "https://wallpapercave.com/wp/wp14808672.webp",
    ],
    year: 2022,
    awards: [
      "Game of the Year",
      "Best Game Direction",
      "Best Art Direction",
      "Best RPG",
    ],
    description:
      "Rise, Tarnished, and explore a massive open world filled with challenging bosses, deep lore, and dark fantasy visuals crafted by FromSoftware.",
    rating: 4.9,
    isWinner: true,
    category: "Game of the Year",
    platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X"],
    recommendedSystemRequirements: {
      os: "Windows 10 / 11 (64-bit)",
      processor: "Intel Core i7-8700K / AMD Ryzen 5 3600X",
      memory: "16 GB RAM",
      graphics: "NVIDIA GeForce GTX 1070 / AMD Radeon RX Vega 56",
      vram: "8 GB",
      directX: "Version 12",
      storage: "60 GB available space (SSD recommended)",
    },
  },
  {
    id: 2021,
    title: "It Takes Two",
    developer: "Hazelight Studios",
    images: [
      "https://wallpapercave.com/wp/wp14614899.jpg",
      "https://wallpapercave.com/wp/wp14614900.jpg",
      "https://wallpapercave.com/wp/wp14614906.jpg",
      "https://wallpapercave.com/wp/wp14614909.jpg",
      "https://wallpapercave.com/wp/wp14614912.jpg",
    ],
    year: 2021,
    awards: ["Game of the Year", "Best Family Game", "Best Multiplayer Game"],
    description:
      "An genre-bending co-op adventure platformer built purely for two players, exploring themes of relationships through highly varied gameplay.",
    rating: 4.8,
    isWinner: true,
    category: "Game of the Year",
    platforms: [
      "PC",
      "PS4",
      "PS5",
      "Xbox One",
      "Xbox Series X",
      "Nintendo Switch",
    ],
    recommendedSystemRequirements: {
      os: "Windows 10 (64-bit)",
      processor: "Intel Core i5-3570K / AMD FX-8350",
      memory: "16 GB RAM",
      graphics: "NVIDIA GeForce GTX 980 / AMD Radeon R9 290X",
      vram: "4 GB",
      directX: "Version 11",
      storage: "50 GB available space",
    },
  },
];
